#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testAdminRequired(self):
        b = self.browser

        self.login_and_go("/snapraid", superuser=False)
        b.wait_in_text(".pf-v6-c-alert__title", "Administrative access required")
        b.wait_in_text(".pf-v6-c-alert", "Only administrators can view or operate the SnapRAID array.")
        b.wait_not_present(".pf-v6-c-tabs")
        b.wait_not_present("button:contains('Run maintenance')")


if __name__ == '__main__':
    testlib.test_main()
